AWSTemplateFormatVersion: 2010-09-09
Description: ''
Resources:
  rdsDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'false'
      BackupRetentionPeriod: '7'
      DBInstanceIdentifier: MyRdsDemo
      DBName: cog
      VPCSecurityGroups:
        - !Ref rdsSecurityGroup
      Engine: postgres
      EngineVersion: '9.5.20'
      MasterUsername: javahome
      MasterUserPassword: oneforalljava
      MultiAZ: 'false'
      Port: '5432'
      PubliclyAccessible: 'true'
      StorageType: gp2
      Tags:
        - Key: Name
          Value: MyRdsDemo
  rdsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow RDS Connections
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: RDSSecurityGroup
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref rdsDBInstance
